[package]
name = "smoltcp-maybe-bug"
version = "0.1.0"
authors = ["iamwwc <qaq1362211689@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun = "0.5.1"
smoltcp = "0.7.3"